version: '3'
services:
    weatherfrontend:
      image: ollieflld/weatherfrontend:latest
      container_name: weatherfrontend
      restart: 'unless-stopped'
      privileged: true
      environment:
        BACKEND_URL: "http://192.168.0.23:18080"
      tty: true