version: '3'
services:
    weatherfrontend:
      image: ollieflld/weatherfrontend:latest
      container_name: weatherfrontend
      restart: 'unless-stopped'
      environment:
        BACKEND_URL: "http://192.168.0.23:18080"
      devices:
        - /dev/i2c-1:/dev/i2c-1
        - /dev/spidev0.0:/dev/spidev0.0
        - /dev/spidev0.1:/dev/spidev0.1